apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmsql-deplyment
  labels:
    name: mmsql-deplyment
    app: microservice-seguridad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-seguridad
      name: mssql-pod
  template:
    metadata:
      name: mssql-pod
      labels:
        app: microservice-seguridad
        name: mssql-pod
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server
          env:
          - name: ACCEPT_EULA # Permite acceder con usuario sa
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            value: "+EbGIv17=x"
          ports:
            - containerPort: 1433